// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DbCont))]
    partial class DbContModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("backend.Modeli.Poslovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("posao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "a"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "b"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "c"
                        });
                });

            modelBuilder.Entity("backend.Modeli.Radnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IdPosla")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("radnik");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdPosla = 1,
                            Ime = "Radnik1",
                            Lozinka = "1",
                            Prezime = "pre1"
                        },
                        new
                        {
                            Id = 2,
                            IdPosla = 2,
                            Ime = "Radnik2",
                            Lozinka = "1",
                            Prezime = "pre2"
                        },
                        new
                        {
                            Id = 3,
                            IdPosla = 3,
                            Ime = "Radnik3",
                            Lozinka = "1",
                            Prezime = "pre3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
